import {GuildMember} from "discord.js";
import {newDiscordMemberChannelId} from "../../config.json";
import {generateJoinMessage} from "../modules/welcomeMessage";

export default {
    name: 'guildMemberAdd',
    async execute(member: GuildMember) {
        const welcomeChannel = await member.guild.channels.fetch(newDiscordMemberChannelId);

        if (welcomeChannel === null || !welcomeChannel.isTextBased() || !welcomeChannel.isSendable()) {
            return;
        }

        generateJoinMessage(member.displayName).then(message => {
            welcomeChannel.send({
                content: member.toString(),
                embeds: [{
                    description: `${message}`,
                    color: 0xffffff,
                    footer: {
                        text: 'Disclaimer: This message was generated by AI'
                    },
                    thumbnail: {
                        url: member.guild.iconURL() || ''
                    }
                }],
            });
        });
    },
};

