const {newDiscordMemberChannelId} = require("../../config.json");
const {generateJoinMessage} = require("../modules/AIReply");

module.exports = {
    name: 'guildMemberAdd',
    async execute(member) {
        const welcomeChannel = await member.guild.channels.fetch(newDiscordMemberChannelId);

        generateJoinMessage(member.displayName).then(message => {
            welcomeChannel.send({
                content: member.toString(),
                embeds: [{
                    description: `${message}`,
                    color: 0xffffff
                }],
                footer: {
                    text: 'Disclaimer: This message was generated by AI'
                },
                thumbnail: {
                    url: member.guild.iconURL()
                }
            });
        });
    },
};

